name: Version

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - version-pipeline

jobs:
  check-version:
    name: Check Version Update
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Get version of main
        id: version-main
        run: |
          version_main=$(grep version setup.py)
          echo "::set-output name=VERSION_MAIN::${version_main}"
      - name: Checkout head branch
        uses: actions/checkout@v2
      - name: Get version head
        id: version-head
        run: |
          version_head=$(grep version setup.py)
          echo "::set-output name=VERSION_HEAD::${version_head}"
      - name: Compare
        run: |
          if [ "${{ steps.version-main.outputs.VERSION_MAIN }}" != "${{ steps.version-head.outputs.VERSION_HEAD }}" ]; then exit 0; fi
      - name: Determine relevant changes
        run: |
          diff_files=$(git diff origin/main.. --name-only | grep -E 'setup.py|orfino/')
          echo Relevant changes in following files: $diff_files
          if [ -z "$diff_files" ]; then exit 0; else exit 1; fi