name: Version

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    name: Check Version Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        # with:
        #   PATTERNS: |
        #     +orfino/*
        #     setup.py
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
        if: env.GIT_DIFF_FILTERED
      - name: Get version of main
        id: version-main
        run: |
          version_main=$(grep version setup.py)
          echo "::set-output name=VERSION_MAIN::${version_main}"
        if: env.GIT_DIFF_FILTERED
      - name: Checkout head branch
        uses: actions/checkout@v2
        if: env.GIT_DIFF_FILTERED
      - name: Get version head
        id: version-head
        run: |
          version_head=$(grep version setup.py)
          echo "::set-output name=VERSION_HEAD::${version_head}"
        if: env.GIT_DIFF_FILTERED
      - name: Compare versions
        id: new-version
        run: |
          new_version=false
          if [ "${{ steps.version-main.outputs.VERSION_MAIN }}" != "${{ steps.version-head.outputs.VERSION_HEAD }}" ]; then new_version=true; fi
          echo "New version in setup.py: $new_version"
          echo "::set-output name=NEW_VERSION::${new_version}"
        if: env.GIT_DIFF_FILTERED